import { Geist, Geist_Mono,Inter, Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "@/component/Navbar/Navbar";
import { ClerkProvider } from "@clerk/nextjs";
import Footer from "@/component/Footer/Footer";
import ToastProvider from "@/component/ToastProvider/ToastProvider";


const inter = Inter({
  subsets: ['latin'],
  weight: ['400', '700'], // optional
  display: 'swap', // optional for performance
})

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '700'],
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased ${roboto.className}` }
      >
        
        <ToastProvider/>
        <div className="w-[100%] min-h-screen overflow-x-hidden bg-white text-black m-auto relative">
          <Navbar />
          {children}
          <Footer/>
        </div>
      </body>
    </html>
    </ClerkProvider>
  );
}
